import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import {
  DynamicContextProvider,
  DynamicWidget,
} from '@dynamic-labs/sdk-react-core';
import { EthereumWalletConnectors } from '@dynamic-labs/ethereum';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { http } from 'viem';
import { mainnet } from 'viem/chains';
import { BitcoinWalletConnectors } from "@dynamic-labs/bitcoin";


const queryClient = new QueryClient();

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicContextProvider
          settings={{
            environmentId: process.env.DYNAMIC_ENVIROMENT_ID!,
            walletConnectors: [BitcoinWalletConnectors]
          }}>
          {children}
        </DynamicContextProvider>
      </body >
    </html >
  );
}
